// Generated by `bun init`

declare module "*.svg" {
    /**
     * A path to the SVG file
     */
    const path: `${string}.svg`;
    export = path;
}

declare module "*.webp" {
    /**
     * A path to the WebP image file
     */
    const path: `${string}.webp`;
    export = path;
}

declare module "*.avif" {
    /**
     * A path to the AVIF image file
     */
    const path: `${string}.avif`;
    export = path;
}

declare module "*.css" {
}

declare module "*.module.css" {
    /**
     * A record of class names to their corresponding CSS module classes
     */
    const classes: { readonly [key: string]: string };
    export = classes;
}
